services:
  recruteurdb:
    container_name: Recruteur-Database
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=${RECRUTEUR_DB_NAME}'
    env_file: .env
    ports:
      - '${RECRUTEUR_DB_PORT}'
    volumes:
      - ./recruteurstorage:/data/postgres

  recruteurms:
    container_name: Recruteur-MS
    build:
      context: .
      dockerfile: Dockerfile
    image: "recruteurms:latest"
    env_file: .env
    ports:
      - "${SPRING_RECRUTEUR_PORT}:${SPRING_RECRUTEUR_PORT}"
